S3/T12 Have a deployment option to set up access to objects from users
baobabsoluciones/cornflow pull request #267
Opened 2022-04-18 06:56 UTC by JaimeSotomayor

Depending on the value of DefaultConfig.USER_ACCESS_ALL_OBJECTS user can access objects of other users or not

2022-04-18 14:30 UTC, JaimeSotomayor commented on cornflow-server/cornflow/tests/unit/test_instances.py
> +            expected_status=404,
@ggsdc revisar aquí si mantener el 404

2022-04-18 16:13 UTC, ggsdc requested changes

2022-04-19 08:26 UTC, ggsdc submitted a review, later dismissed

2022-04-19 08:28 UTC, ggsdc commented
One last change and we are good to merge, can you add the following code:

```python
USER_ACCESS_ALL_OBJECTS = os.getenv("USER_ACCESS_ALL_OBJECTS", 0)
os.environ["USER_ACCESS_ALL_OBJECTS"] = str(USER_ACCESS_ALL_OBJECTS)
```

On the `init_cornflow_service.py` file on line 63?

2022-04-19 08:49 UTC, ggsdc approved these changes

2022-04-19 09:05 UTC, merged