Feature/example dag data
baobabsoluciones/cornflow pull request #277
Opened 2022-04-29 12:19 UTC by JaimeSotomayor

Closes #89

2022-05-01 10:02 UTC, ggsdc requested changes
You need to make several changes in order for the PR to work and make sense.
**DO NOT COPY CODE WITHOUT UNDERSTANDING IT**

2022-05-01 10:02 UTC, ggsdc commented on cornflow-server/cornflow/endpoints/example_data.py
> +            log.debug("User gets exampple data from {}".format(dag_name))
exampple -> example

2022-05-01 10:02 UTC, ggsdc commented on cornflow-server/cornflow/tests/unit/test_example_data.py
> +        af_client.get_dag_info.assert_called_once()
In this case this test should be on the integration folder

2022-05-01 10:33 UTC, ggsdc commented
One more thing. Once this PR is closed and the DAG is accepted, you should open an similar PR on cornflow-dags (the private repo) bringing this changes as well.

2022-05-05 15:24 UTC, JaimeSotomayor commented on cornflow-dags/DAG/dag_timer.py
> +        return list()
imported

2022-06-03 09:07 UTC, ggsdc approved these changes

2022-06-03 09:42 UTC, merged