Feature/generalizing methods dag
baobabsoluciones/cornflow pull request #360
Opened 2023-01-26 13:15 UTC by AlejandroMus

2023-01-27 10:35 UTC, ggsdc reviewed
Will review it after the other PR is merged

2023-02-02 12:11 UTC, ggsdc requested changes
You should add some tests to these methods

2023-02-07 11:06 UTC, ggsdc requested changes

2023-02-07 11:06 UTC, ggsdc commented on libs/client/cornflow_client/core/instance_solution.py
> +
This method is not getting tested

2023-02-07 11:06 UTC, ggsdc commented on libs/client/cornflow_client/core/instance_solution.py
> +        return self.get_hour_from_ts(self.get_datetimesec_from_string(string))
These methods are not getting tested

2023-02-07 21:09 UTC, ggsdc commented
Just as a good practice. All these commits where pushed together to the repo: 

![image](https://user-images.githubusercontent.com/24654620/217365861-1a79b478-95c1-40a0-8483-774b8c95fddb.png)

That can be seen because just the last one is the one that launched the automated workflows. When working on your local machine, you can ammend the commit and add more changes if the commit has not been pushed to the remote, that way all those commits could be just one.

2023-02-07 21:09 UTC, ggsdc submitted a review, later dismissed

2023-02-07 21:10 UTC, ggsdc commented
Will wait for the other PR to be merged before merging this one

2023-02-08 08:12 UTC, marioncottard submitted a review, later dismissed

2023-02-13 19:29 UTC, ggsdc approved these changes

2023-02-13 19:29 UTC, merged