Bugfix/review commands
baobabsoluciones/cornflow pull request #574
Opened 2024-12-02 16:24 UTC by marioncottard

Fixes https://github.com/baobabsoluciones/cornflow/issues/496. Note that for the commands to work properly for external apps, the environment variable `DEFAULT_POSTGRES` needs to be defined.
Closes https://github.com/baobabsoluciones/cornflow/issues/567.

2024-12-04 11:39 UTC, ampuerin approved these changes

2025-02-26 09:00 UTC, ggsdc requested changes
Small change, but I guess that you have tested that the cornflow cli is fully usuable from inside the container right? The main use for this will be the user creation / handling and we can addmore commands in that sense

2025-02-26 09:00 UTC, ggsdc commented on cornflow-server/cornflow/cli/migrations.py
> +        downgrade()
For the downgrade you should pass a migration file name or version to downgrade to that version. 
We could also do that for the upgrade as well.

2025-03-06 10:18 UTC, ggsdc commented
@marioncottard when do you think are you going to be able to tackle these changes?

2025-03-11 14:52 UTC, merged